dependencies:
  # - <organization/repo>@<version
  - smartcontractkit/chainlink-brownie-contracts@1.1.1

compiler:
  solc:
    # remap chainlink to a github repo
    remappings:
      - '@chainlink=smartcontractkit/chainlink-brownie-contracts@1.1.1'

# use .env
dotenv: .env
